spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DomizianoDeSantis/ecommerce-config.git
          username: ${github_username}
          password: ${github_password}

server:
  port: 8888